### PR TITLE
update vid2vid.py

### PR DESCRIPTION
**Pull request by orcist**
cleaner code, seed walking option

### CODE REVIEW

**Comment by ClashSAN** [comment]
@Filarius could you setup a clean repo for your script? It will be linked to wiki.

**Comment by Filarius** [comment]
@ClashSAN  i will try to take my hands on it

**Comment by Filarius** [comment]
not sure what i did, i wish its going good ? @orcist

**Comment by orcist** [comment]
@Filarius seems alright, you can delete the branch :)

**Comment by Filarius** [comment]
@orcist  well, i dont see any beside `master`
soon i will make separate repo with just few files, this repo was made just in talk with my friend.

**Comment by orcist** [comment]
ah, so the branch was in my temporary fork that github made just for the PR right?

**Comment by Filarius** [comment]
@orcist i took a look into your PR. Thanks to clearning my dirty code. And i don't agree with idea about random seed step - its dont persistent/repeat-able. Also that part about changing seed, by my thoughts, all must be wrapped into `if` statement. 

Do you made investigation how to make video frames smoother. Like latent interpolation or something ?

**Comment by orcist** [comment]
@Filarius the model function is not clean, i.e. not even a specific seed can guarantee an exact result, but it's very close if you use all the same parameters and inputs.

If the overall color composition of the input clip doesn't change very much, or if you inpaint only more static sections of the input videoclip you can achieve a "cartoony" animation. You can also achieve a nice morphing effect if the composition is similar but you change the query and gradually increase or decrease denoising strength. There is a problem with output composition changing rapidly sometimes, due to a dynamic input scene, but one could sort the frames in [order of similarity](https://towardsdatascience.com/measuring-similarity-in-two-images-using-python-b72233eb53c6) to get a more fluid result, possibly toss some frames with high distance. I'm going to go out on a limb and blindly suggest that maybe one could also alpha blend a few neighboring frames and run additional denoising loops over the result to make the sequences more fluid.

I plan to add both inpainting and denoising controls soon, not exactly sure about the rest - could use some help.

I demoed some of these effects in [this animation (link)](https://youtu.be/ceVmxHzDW3k).

**Comment by orcist** [comment]
I opened PR https://github.com/Filarius/stable-diffusion-webui/pull/2 here, I made a typo in the `seed_step` condition sorry

**Comment by Filarius** [comment]
@orcist inpaint of video ? Only static image-mask or video-mask ? Some time ago i was curious if there simple free app who can help easy creation of video-mask.

i had try on meme-video based on movie, and i dont like neightboor frames (who is like looks like pretty similar) had too different result. So i'm thinking to learn how to make thing like latent interpolation at plugin level, but not sure if i can get it.
Over idea i had last time is a content based blending. Like make blend between frames, but use OpenCV to split images into areas (triangles ?) and blend on it, so it must solve ghosting problem (not sure if its even worth to care about, and just make usual blending between images to smooth noise and not-a-similar-ness

**Pull request merged**
